### ISSUE TITLE
Can't use sinon.spy with function that has nonzero length

### ISSUE THREAD

**Issue by dmnd** [atom/loophole#1]
I'm trying to use `loophole` because [`sinon.spy` uses `eval` to define a function with arguments](https://github.com/cjohansen/Sinon.JS/blob/0fea852e50be68aa76dec6209721fca870b324d1/lib/sinon/spy.js#L70).

Here's an example of how I'm using it:

``` coffeescript
{allowUnsafeEval} = require 'loophole'
sinon = require 'sinon'

describe "loophole and sinon"
  it "should be able to use spy", ->
    obj = fn: (a) -> a

    spy = null
    allowUnsafeEval ->
      spy = sinon.spy(obj, 'fn')

    obj.fn 1
    assert spy.calledOnce
```

But I end up with the following:

```
TypeError: Cannot set property 'reset' of undefined
at Object.extend (/Users/dmnd/github/linter/node_modules/sinon/lib/sinon/extend.js:68:38)
at Function.create (/Users/dmnd/github/linter/node_modules/sinon/lib/sinon/spy.js:125:23)
at Object.spy (/Users/dmnd/github/linter/node_modules/sinon/lib/sinon/spy.js:34:59)
at statusbar-view-spec.coffee:56:19
at exports.allowUnsafeEval (/Users/dmnd/github/linter/node_modules/loophole/lib/loophole.js:14:14)
at statusbar-view-spec.coffee:55:5
```

It seems that when `sinon` tries to create the new function, the overridden `eval` returns null.

**Comment by beck** [comment]
Seems like this issue is now ruining the build for all tests that stub.

**Comment by gandm** [comment]
I am also developing specs for my package in Atom that are trying to stub the fs. I too get the original unsafe-eval message and when using the loophole package I get reset undefined! I'd like to be able to stub this!

```stubWriteFileSync = sinon.stub(fs, 'writeFileSync').return(undefined)```
 gets
![image](https://cloud.githubusercontent.com/assets/2313237/7977966/1033f016-0a88-11e5-9715-8e0f7ad442f9.png)

whereas
```      allowUnsafeEval ->
        stubWriteFileSync = sinon.stub(fs, 'writeFileSync').return(undefined)```
gets
![image](https://cloud.githubusercontent.com/assets/2313237/7977996/566b87ba-0a88-11e5-85ba-d7722e7e518a.png)

**Comment by stevemao** [comment]
If `spy = sinon.spy(obj, 'fn')` underneath using local var then no :disappointed: 

https://nodejs.org/api/vm.html#vm_vm_runinthiscontext_code_options
`vm.runInThisContext` does not have access to the local scope, so `localVar` is unchanged.
